username= input("enter the username:")
password= input("enter the password:")

if username=="Admin" and password=="Admin":

    print("user logon successful")

else:
    print("user logon failed")    




username= input("enter the username:")
password= input("enter the password:")

if username=="Admin" or password=="Admin":

    print("user logon successful")

else:
    print("user logon failed") 
