# sort() sorting elements of a list in either ascending or descending order
# By default ascending is false
L1= [10,30,50,70,60,20,80,40]
L1.sort()
print(L1)

# sort in descending we can use reverse=True parameter
L2= [10,30,50,70,60,20,80,40]
L2.sort(reverse=True)
print(L2)

# we can sort the list using string data also

result='D'
print(ord(result))


result='a'
print(ord(result))

result=88
print(chr(result))